### ISSUE TITLE
Not incrementing versions in AndroidManifest

### ISSUE THREAD

**Issue by olegdizus** [stovmascript/react-native-version#14]
```android:versionCode``` and ```android:versionName``` fields

**Comment by stovmascript** [comment]
Hey @olegdizus. I think RN updates these values in memory during build time. Looking at RN projects I've worked on, I see that they always stay at their default values:

```xml
<manifest
	android:versionCode="1"
	android:versionName="1.0"
```

Why do you need them to be updated?

**Comment by jsdario** [comment]
It seems to me that they are mandatory for the play store, aren't they?

**Comment by stovmascript** [comment]
@jsdario I don't dispute that. I'm just saying that I've never seen this file updated since doing `react-native init`, therefore I don't think RNV should update them either.

When you're building an APK for the Play Store, they should be updated during the build process. Or am I missing something?

**Comment by stovmascript** [comment]
I think React Native's behaviour in this case is indeed weird, but it makes sense to update the values only in the Gradle file. Or vice versa, but definately not in two places.

**Comment by stovmascript** [comment]
But I would still like to know if there's any interesting use case that would warrant updating AndroidManifest.xml because we could then make an extra option for it :)

**Comment by matthewphiong** [comment]
@stovmascript @jsdario Updating AndroidManifest.xml will not have any effect since the ones written in build.gradle will replace the ones in AndroidManifest.xml during build.

But it might be a good idea to also update the values in AndroidManifest.xml to clear any confusion created by different values of `versionCode` and `versionName` in build.gradle and AndroidManifest.xml

**Comment by jsdario** [comment]
The PR above is just a draft on how it was implemented under the organisation I work in. Feel free to copy / paste, improve or close it.

Hope it helps.

**Comment by stovmascript** [comment]
@jsdario Ok, thanks. Will have a deeper look at it later.

**Comment by stovmascript** [comment]
I think updating AndroidManifest.xml is out of the scope of this package. RNV's job should be to update the topmost values, which you'd otherwise have to update manually in a RN app. Android manifest files get updated dynamically during build, which is what RN users expect, so updating them with RNV would actually create confusion.
