### ISSUE TITLE
Feature Request: Update app.json regardless of Expo

### ISSUE THREAD

**Issue by victoriafrench** [stovmascript/react-native-version#143]
The latest React Native for Android can not import package.json (see [#25645](https://github.com/facebook/react-native/issues/25645)).

The current release will update app.json if the project is expo, but won't update it for normal apps. It would be great if the detection would update app.json if version exists in it regardless of the expo flag. This would allow us to work around the react-native issue without requiring a third-party lib.

**Comment by stovmascript** [comment]
I'm not catching on with reference to that RN issue. Can you clarify how you're using RNV?

- app.json is only updated for Expo apps, ejected or non-Expo apps get modified in native code
- if you want to display the version number inside your app, you should use: https://github.com/APSL/react-native-version-number

**Comment by victoriafrench** [comment]
that will work too, wasn't aware of that. but if the app.json were being updated instead of being ignored, wouldn't have to use another library at all.

**Comment by stovmascript** [comment]
I understand, but I think it would make RNV unpredictable if it was updating values in places it shouldn't.

app.json is only updated for Expo apps because that's the only place Expo apps read version info. If the app is ejected (or non-Expo), RNV will default back to updating native code because that's the only place the version info can be read inside the app.
