### ISSUE TITLE
Doesn't update the iOS project version number

### ISSUE THREAD

**Issue by tmchow** [stovmascript/react-native-version#71]
For our XCode project, we have the version number defined in the project (`project.pbxproj`) in variable `CURRENT_PROJECT_SETTINGS`. 

The project has 2 targets, my app and one of our 3rd party dependencies.  In the info.plist files for each, we set the version numbers to the variable `$(CURRENT_PROJECT_SETTINGS)` so we update the version in one place (at the project level) which then gets referenced by all the targets.  This is a common pattern we've found recommended.

When we try to use `react-native-version`, the target's build settings get their version numbers updated in their respective `info.plist`, but the `project.pbxproj` file is untouched.

For example, if my version was currently `1.0.0`, and i update the patch number, I see `1.0.1` in the info.plist for both targets, but the `CURRENT_PROJECT_VERSION` is left untouched as `1.0.0`

Is the right way to handle this just to abandon our use of `CURRENT_PROJECT_NUMBER` and delete it from our `project.pxproj` file? Or is there a way to have react-native-version update our project level version and not at the info.plist level of each target?

**Comment by stovmascript** [comment]
@tmchow You shouldn't have to update anything in your Xcode project manually. RNV takes the version number from your `package.json` and injects it everywhere, including this variable. Take a look at the [test fixtures](https://github.com/stovmascript/react-native-version/tree/master/test/fixtures) or init a clean React Native project somewhere to see how to set up your project accordingly.

The thing that might be out of the ordinary, is the 2 targets that you have to build.

If it doesn't work after checking/setting up your project according to the default RN project, could you maybe make a sample repo with a clean RN project and then set the 2 targets similarly to how you have it in your real project?

**Comment by tmchow** [comment]
@stovmascript my project was setup originally with the target’s each having a reference to the version defined by the project. 

Meaning that the info.plist of each target referenced `$(CURRENT_PROJECT_VERSION)`. 

When I then ran `yarn version` to bump the version number, the targets would not get their version updated properly. It would bump it to `NaN`. 

So I then changed the references to the current project variable to an absolutel version number (eg. `$(CURRENT_PROJECT_VERSION)` -> `1.0.0`). 

When I then re-ran yarn version, the version number got bumped correctly but the version in the project wasn’t updated.

**Comment by stovmascript** [comment]
@tmchow I see now. You're putting the version string (`1.0.0` or in iOS speak: `CFBundleShortVersionString`) into `CURRENT_PROJECT_VERSION`, but [React Native puts the build number integer (`CFBundleVersion`) into this variable](https://github.com/stovmascript/react-native-version/blob/master/test/fixtures/AwesomeProject/ios/AwesomeProject.xcodeproj/project.pbxproj#L1208).

I suggest resetting this to match a clean RN project, otherwise RNV won't work properly.

P.S. My test fixture is a bit out of date, but I just checked the RN repo and [it's still done the same way](https://github.com/facebook/react-native/blob/896bb8a21e947fb7af1132d1e3da58785ed93099/template/ios/HelloWorld.xcodeproj/project.pbxproj#L1217).
