### ISSUE TITLE
Allow for skipping tags in all cases regardless of amend vs no amend

### ISSUE THREAD

**Issue by tmchow** [stovmascript/react-native-version#72]
I see the existing option of `--skip-tag` but this only works when you're amending.  Since we use external build systems (buddybuild) which creates our tags for us, we never want to generate tags based on the version bump.

I suggest the `--skip-tags` always allows  control of whether tags are created.

**Comment by stovmascript** [comment]
@tmchow RNV doesn't actually create tags, the `--skip-tag` option is there because it makes sense to update Git tags created by `npm version ...` by default. However, this is only done when you add RNV to the "version" or "postversion" npm script. In all other situations, RNV only bumps versions and it's up to the user to commit the changes and update any Git tags.
