### ISSUE TITLE
react-native-version inside git hook

### ISSUE THREAD

**Issue by loic-lopez** [stovmascript/react-native-version#93]
Hello,

I think it may be good to have an option with `react-native-version` and with the option `--amend`.

This option is as follows: if `react-native-version` is used in a `pre-commit` hook this results from an infinite loop.

In order to resolve this issue i think it may be nice if we can pass the `--no-verify` option from Git.
See: [--no-verify option from Git](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---no-verify)

Thanks for reply.

**Comment by stovmascript** [comment]
@loic-lopez Hi. How are you using RNV inside a pre-commit hook? Can you clarify your workflow a bit more? It seems kind of wild to be versioning your app automatically. How do you control the resulting version number?

**Comment by loic-lopez** [comment]
Thanks for your response,

I'm using : [typicode/husky](https://github.com/typicode/husky) for managing my git hooks and the configuration looks like this:

```json
{
  "hooks": {
    "pre-commit": "yarn run react-native-version --never-amend",
    "post-commit": "git add android ios && git commit -am 'bump build version' --no-verify"
  }
}
```

I'm using this hook only for increment the **_build number_** not for change the _**version number**_

But does is it a good practice?

**Comment by stovmascript** [comment]
Well typically you would increment the version or build number when you're making a new build for test distribution or release, so I don't think bumping the build number for every commit is a good idea. It implies that there have been X many releases since the last distributed build and I doubt you distribute a new build after every new commit (?).

Also, I think with your setup the infinite loop is caused by your post-commit hook, which makes another commit, therefore triggers another round of pre-commit, post-commit hooks.

**Comment by loic-lopez** [comment]
So build version must be done manually?

**Comment by stovmascript** [comment]
If you only what to increment the build number, use: `react-native-version --increment-build`.

You can try adding that to your pre-commit hook and see if it works the way you want.

**Comment by loic-lopez** [comment]
So finally i have set up a build hook : when a pull request is merged the build version is incremented by 1.
